version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: 'mssql2019-linux'
    environment:
      - MSSQL_SA_PASSWORD={任意のパスワード}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer # default: Developer
      # - MSSQL_PID=Express
      # - MSSQL_PID=Standard
      # - MSSQL_PID=Enterprise
      # - MSSQL_PID=EnterpriseCore
    ports:
      - 14330:1433
    volumes: # Mounting a volume does not work on Docker for Mac
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/data:/var/opt/mssql/data

  redis:
    image: "redis:latest"
    container_name: 'redis-linux'
    ports:
      - "63790:6379"
    volumes:
      - "./redis/data:/data"
